"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[username]
show_always = true

[golang]
symbol = "î˜§ "
style = "bold blue"


[aws]
disabled = true

[terraform]
disabled = true

